version: "3.4"
services:
  mariadb:
    image: mariadb:10

    container_name: poslive-mariadb
    
    ports:
      - 3306:3306

    restart: on-failure

    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123

    volumes:
      - poslive:/var/lib/mysql

  rabbitmq:
        image: rabbitmq:3.10-management
        container_name: rabbitmq
        restart: always

        ports:
            - 5672:5672
            - 15672:15672

        volumes:
        - ./dados:/var/lib/rabbitmq/

        environment:
            - RABBITMQ_DEFAULT_USER=root
            - RABBITMQ_DEFAULT_PASS=123
  
  zipkin:
    image: openzipkin/zipkin

    container_name: zipkin

    ports:
      - 9411:9411

volumes:
  poslive: